### ISSUE TITLE
Question: Fetch all values

### ISSUE THREAD

**Issue by ostjen** [Level/level#201] opened 2021-07-12 14:09 UTC
Is there a way to fetch all values without creating a stream?

context: I'm writing a method that returns the last N entries in the database.

**Comment by vweevers** [comment] 2021-07-12 14:13
Duplicate of https://github.com/Level/levelup/issues/491. Short answer: you can use an iterator instead of a stream, but there's no dedicated simple API for fetching multiple values.

**Closed by vweevers** 2021-07-12 14:13 UTC

**Comment by ostjen** [comment] 2021-07-12 15:00
@vweevers is there any example of the correct usage of the iterator? I can only access the last value, when I try to actually iterate over it all values end up being undefined

**Comment by vweevers** [comment] 2021-07-12 15:12
Roughly:

```js
function collectLast (limit, callback) {
  const iterator = db.iterator({ reverse: true, limit })

  const end = function (err) {
    iterator.end(function (err2) {
      callback(err || err2)
    })
  }

  const loop = function () {
    iterator.next((err, key, value) => {
      if (err) return end(err)

      if (key === undefined && value === undefined) {
        // reached the end
        return end()
      }
      
      // do something with key & value
      // ..

      loop()
    })
  }

  loop()
}
```

**Comment by ostjen** [comment] 2021-07-12 16:15
Thanks, it worked! :smile:

**Comment by vweevers** [comment] 2021-07-12 16:19
Oh I forgot about https://github.com/Level/concat-iterator :)
