### ISSUE TITLE
Could not find a declaration file for module 'level'

### ISSUE THREAD

**Issue by sagaratalatti** [Level/level#121] opened 2018-10-17 12:02 UTC
I have add the level package to my javascript project. But I get an error on Visual Studio Code.

```
{
  "name": "project_2",
  "version": "1.0.0",
  "description": "Blockchain has the potential to change the way that the world approaches data. Develop Blockchain skills by understanding the data model behind Blockchain by developing your own simplified private blockchain.",
  "main": "simpleChain.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/levelup": "^3.1.0",
    "crypto-js": "^3.1.9-1",
    "level": "^4.0.0"
  }
}
```
[ts]
Could not find a declaration file for module 'level'. 'c:/n/Project_2/node_modules/level/level.js' implicitly has an 'any' type.
  Try `npm install @types/level` if it exists or add a new declaration (.d.ts) file containing `declare module 'level';`

**Comment by vweevers** [comment] 2018-10-17 12:05
Duplicate of #120.

**Closed by vweevers** 2018-10-17 12:05 UTC
