### ISSUE TITLE
TypeError: exists is not a function

### ISSUE THREAD

**Issue by caalberts** [Level/level#34] opened 2015-11-18 16:34 UTC
Hi, I'm getting this error when using Level.

Console shows the error here, which is in bindings module:

```
exports.getRoot = function getRoot (file) {
  var dir = dirname(file)
    , prev
  while (true) {
    if (dir === '.') {
      // Avoids an infinite loop in rare cases, like the REPL
      dir = process.cwd()
    }
    if (exists(join(dir, 'package.json')) || exists(join(dir, 'node_modules'))) {
      // Found the 'package.json' file or 'node_modules' dir; we're done
      return dir
    }
```

**Comment by ralphtheninja** [comment] 2015-11-18 17:35
@caalberts Do you have the error log from the console by any chance as well?

**Comment by juliangruber** [comment] 2015-11-19 00:37
this is from the bindings module:

```js
  , exists = fs.existsSync || path.existsSync
```

I wouldn't know which node version didn't have support for that. What node are you running on?

**Comment by juliangruber** [comment] 2015-11-19 00:37
also, can you tell us the output of

```js
console.log(fs.existsSync || path.existsSync)
```

**Comment by ralphtheninja** [comment] 2015-11-19 01:17
I noticed this https://github.com/TooTallNate/node-bindings/issues/18

**Comment by kaivalya90** [comment] 2016-08-10 18:43
I still got the same error even after the change.
  while (true) {
    if (dir === '.') {
      // Avoids an infinite loop in rare cases, like the REPL
      dir = process.cwd()
    }
    if (exists(join(dir, 'package.json')) || exists(join(dir, 'node_modules'))) {
      // Found the 'package.json' file or 'node_modules' dir; we're done
      return dir
    }
    bindings.js:154Uncaught TypeError: exists is not a function

Does anyone face the same issue?

Thanks,

**Comment by juliangruber** [comment] 2016-08-10 18:55
@kaivalya90 which node version are you on?

**Comment by kaivalya90** [comment] 2016-08-10 18:57
E:\angularJS\XXxxCap>meteor node --version
v4.4.7

**Comment by juliangruber** [comment] 2016-08-10 19:18
node@4 _definitely_ has `fs.existsSync`, the issue must lie elsewhere

**Comment by rmroot** [comment] 2017-02-01 16:36
@kaivalya90 did you ever found out what was going on with that error? I'm running into the same issue

**Comment by Twistedst** [comment] 2017-02-09 15:38
I am also running into this issue. Has anyone figured out a solution?

**Comment by Twistedst** [comment] 2017-02-09 15:41
Found that the fix is in [TooTallNate/node-bindings#20](https://github.com/TooTallNate/node-bindings/pull/20) (as stated above). The PR for the commit is still open though, so it hasn't been updated.

**Comment by Ameobea** [comment] 2017-03-11 04:23
The PR has been accepted; not sure if this library's dependencies have been updated however.

**Comment by fergiemcdowall** [comment] 2018-12-20 14:33
I seem to be getting this as well- also during browserification

**Comment by ralphtheninja** [comment] 2018-12-20 16:05
Would be nice to get to the bottom of this.

**Comment by vweevers** [comment] 2018-12-22 07:45
> I just encountered this error in the browser console while trying to browserify an application containing leveldb

> I seem to be getting this as well- also during browserification

That's expected: `level` only supports Node.js. There is ongoing work to make it work in both Node.js and in the browser. In the meantime, we suggest you to use [level-browserify](https://github.com/level/level-browserify).

**Comment by vweevers** [comment] 2018-12-23 11:50
I'm closing this, as it's not a bug, but a missing feature, which is covered by #50.

**Closed by vweevers** 2018-12-23 11:50 UTC

**Comment by naveed-31** [comment] 2019-06-11 07:07
stuck on this issue

**Comment by naveed-31** [comment] 2019-06-11 07:08
Stuck on this issue :

ERROR Error: Uncaught (in promise): TypeError: exists is not a function
TypeError: exists is not a function
    at Function.getRoot (bindings.js:205)
    at bindings (bindings.js:84)
    at Object.<anonymous> (pcsclite.js:4)

**Comment by vweevers** [comment] 2019-06-11 07:14
@naveed-31 Latest `level` no longer uses the `bindings` module, so it shouldn't be an issue anymore. Which version are you using?

**Comment by naveed-31** [comment] 2019-06-11 07:29
Actually i am this model `@pokusew` (nfc-pcsc) which uses the bindings module.any idea?

**Comment by vweevers** [comment] 2019-06-11 07:57
@naveed-31 If your issue is not related to `level`, then this is not the right place to discuss it.

**Comment by arturbp** [comment] 2020-11-13 13:58
The same here when trying to using 'usb' lib in ReactJS:

TypeError: exists is not a function

 199 |   // Avoids an infinite loop in rare cases, like the REPL
  200 |   dir = process.cwd();
  201 | }
> 202 | if (
        | ^  203 |   exists(join(dir, 'package.json')) ||
  204 |   exists(join(dir, 'node_modules'))
  205 | ) {



in bindings:

...
  exists =
    (fs.accessSync &&
      function(path) {
        try {
          fs.accessSync(path);
        } catch (e) {
          return false;
        }
        return true;
      }) ||
    fs.existsSync ||
    path.existsSync,
...


node v14.15.0
